

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api/v1.0
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB

aws.access.key=${AWS_ACCESSKEY}
aws.secret.key=${AWS_SECRETKEY}
aws.region=ap-south-1
aws.bucket.name=${BUCKET_NAME}

jwt.secret.key=${JWT_SECRET_KEY}

razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.frontend-url=${APP_FRONTEND_URL}
